name: Build APK
on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setting environment variables for app.
      - name: Create env file
        run: |
          cd ${{ github.workspace }}
          echo "import os
          os.environ['WEB_API_KEY'] = '${{ secrets.WEB_API_KEY }}'
          os.environ['DATABASE_URL'] = '${{ vars.DATABASE_URL }}'" > libs/firebase_config.py
          cat libs/firebase_config.py
      - name: Build with Buildozer
        run: |
          pip3 install --user --upgrade buildozer Cython virtualenv
          export PATH=$PATH:~/.local/bin/
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          export BUILDOZER_WARN_ON_ROOT=0
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          ls -l | grep "api_key.txt"
          buildozer android debug
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
      
      - name: Apk Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: bin/*.apk
